/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package whacamole;
import java.awt.Image;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author compu
 */
public class Grafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Grafica.class.getName());
    private Gestore gestore = new Gestore();
    private ArrayList<JButton> bottoni = new ArrayList<>();
    private javax.swing.Timer timer;
    Gestore punti = new Gestore();
    private Image immagineSfondo;
    
    
    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/images/TalpaVera.png"));

        int nuovaLarghezza = originalIcon.getIconWidth() / 2;
        int nuovaAltezza = originalIcon.getIconHeight() / 2;
        ImageIcon talpaIcon = new ImageIcon(originalIcon.getImage().getScaledInstance(nuovaLarghezza, nuovaAltezza, Image.SCALE_SMOOTH));


    bottoni.add(Bottone1);
    bottoni.add(Bottone2);
    bottoni.add(Bottone3);
    bottoni.add(Bottone4);
    bottoni.add(Bottone5);
    bottoni.add(Bottone6);
    bottoni.add(Bottone7);
    bottoni.add(Bottone8);
    bottoni.add(Bottone9);
    
    
    for (JButton b : bottoni) {
        b.setIcon(talpaIcon);
        b.setBorderPainted(false);
        b.setContentAreaFilled(false);
        b.setFocusPainted(false);
        b.setOpaque(false);
        b.setSize(nuovaLarghezza, nuovaAltezza);
        b.setPreferredSize(new java.awt.Dimension(nuovaLarghezza, nuovaAltezza));
    }
    
        Panel.setLayout(new GridLayout(3, 3, 10, 10));
        for (JButton b : bottoni) {
            Panel.add(b);
        }
        
    Panel.setVisible(false);
    nascondiTutto();

    timer = new javax.swing.Timer(1000, e -> mostraTalpa());
    timer.start();
        
    }
    private void nascondiTutto() {
        for (JButton b : bottoni) {
            b.setVisible(false);
        }
    }
    
    private void mostraTalpa() {
        nascondiTutto();

        int indice = gestore.esciTalpa();
        bottoni.get(indice).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Bottone2 = new javax.swing.JButton();
        Bottone5 = new javax.swing.JButton();
        Bottone3 = new javax.swing.JButton();
        Bottone7 = new javax.swing.JButton();
        Bottone6 = new javax.swing.JButton();
        Bottone8 = new javax.swing.JButton();
        Bottone4 = new javax.swing.JButton();
        Bottone9 = new javax.swing.JButton();
        Bottone1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPunteggio = new javax.swing.JLabel();
        BottoneGioca = new javax.swing.JButton();
        txtTitolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        Bottone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone2ActionPerformed(evt);
            }
        });

        Bottone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone5ActionPerformed(evt);
            }
        });

        Bottone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone3ActionPerformed(evt);
            }
        });

        Bottone7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone7ActionPerformed(evt);
            }
        });

        Bottone6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone6ActionPerformed(evt);
            }
        });

        Bottone8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone8ActionPerformed(evt);
            }
        });

        Bottone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone4ActionPerformed(evt);
            }
        });

        Bottone9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone9ActionPerformed(evt);
            }
        });

        Bottone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        jLabel1.setText("Punteggio: ");

        txtPunteggio.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        txtPunteggio.setText("0");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Bottone7)
                        .addGap(40, 40, 40)
                        .addComponent(Bottone8)
                        .addGap(85, 85, 85)
                        .addComponent(Bottone4))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(Bottone3)
                        .addGap(1861, 1861, 1861)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPunteggio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bottone5)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Bottone9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(Bottone2)))
                        .addGap(36, 36, 36)
                        .addComponent(Bottone6)
                        .addGap(77, 77, 77)
                        .addComponent(Bottone1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(Bottone9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(Bottone5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(Bottone7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(Bottone2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Bottone3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(Bottone8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(Bottone4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                        .addComponent(Bottone6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPunteggio)))
                .addGap(63, 63, 63))
        );

        BottoneGioca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BottoneGioca.setText("Gioca");
        BottoneGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneGiocaActionPerformed(evt);
            }
        });

        txtTitolo.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 36)); // NOI18N
        txtTitolo.setText("Whac-A-Mole");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTitolo)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(BottoneGioca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(214, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(txtTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)
                    .addComponent(BottoneGioca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone1ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone1.setVisible(false);
    }//GEN-LAST:event_Bottone1ActionPerformed

    private void Bottone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone4ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone4.setVisible(false);
    }//GEN-LAST:event_Bottone4ActionPerformed

    private void Bottone7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone7ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone7.setVisible(false);
    }//GEN-LAST:event_Bottone7ActionPerformed

    private void Bottone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone2ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone2.setVisible(false);
    }//GEN-LAST:event_Bottone2ActionPerformed

    private void Bottone5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone5ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone5.setVisible(false);
    }//GEN-LAST:event_Bottone5ActionPerformed

    private void Bottone9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone9ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone9.setVisible(false);
    }//GEN-LAST:event_Bottone9ActionPerformed

    private void Bottone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone3ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone3.setVisible(false);
    }//GEN-LAST:event_Bottone3ActionPerformed

    private void Bottone6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone6ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone6.setVisible(false);
    }//GEN-LAST:event_Bottone6ActionPerformed

    private void Bottone8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone8ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone8.setVisible(false);
    }//GEN-LAST:event_Bottone8ActionPerformed

    private void BottoneGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneGiocaActionPerformed
        Panel.setVisible(true);
        BottoneGioca.setVisible(false);
        txtTitolo.setVisible(false);
    }//GEN-LAST:event_BottoneGiocaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Grafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone1;
    private javax.swing.JButton Bottone2;
    private javax.swing.JButton Bottone3;
    private javax.swing.JButton Bottone4;
    private javax.swing.JButton Bottone5;
    private javax.swing.JButton Bottone6;
    private javax.swing.JButton Bottone7;
    private javax.swing.JButton Bottone8;
    private javax.swing.JButton Bottone9;
    private javax.swing.JButton BottoneGioca;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtPunteggio;
    private javax.swing.JLabel txtTitolo;
    // End of variables declaration//GEN-END:variables
}
