/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package whacamole;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author compu
 */
public class Grafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Grafica.class.getName());
    private Gestore gestore = new Gestore();
    private ArrayList<JButton> bottoni = new ArrayList<>();
    private javax.swing.Timer timer;
    
    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        
        
    bottoni.add(Bottone1);
    bottoni.add(Bottone2);
    bottoni.add(Bottone3);
    bottoni.add(Bottone4);
    bottoni.add(Bottone5);
    bottoni.add(Bottone6);
    bottoni.add(Bottone7);
    bottoni.add(Bottone8);
    bottoni.add(Bottone9);

    nascondiTutto();

    timer = new javax.swing.Timer(1000, e -> mostraTalpa());
    timer.start();
        
    }
    private void nascondiTutto() {
        for (JButton b : bottoni) {
            b.setVisible(false);
        }
    }
    
    private void mostraTalpa() {
        nascondiTutto();

        int indice = gestore.esciTalpa();
        bottoni.get(indice).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bottone1 = new javax.swing.JButton();
        Bottone2 = new javax.swing.JButton();
        Bottone3 = new javax.swing.JButton();
        Bottone4 = new javax.swing.JButton();
        Bottone5 = new javax.swing.JButton();
        Bottone6 = new javax.swing.JButton();
        Bottone7 = new javax.swing.JButton();
        Bottone8 = new javax.swing.JButton();
        Bottone9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bottone1.setText("Talpa1");
        Bottone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone1ActionPerformed(evt);
            }
        });

        Bottone2.setText("Talpa4");

        Bottone3.setText("Talpa7");

        Bottone4.setText("Talpa2");

        Bottone5.setText("Talpa5");

        Bottone6.setText("Talpa8");

        Bottone7.setText("Talpa3");

        Bottone8.setText("Talpa9");

        Bottone9.setText("Talpa6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone1)
                    .addComponent(Bottone2)
                    .addComponent(Bottone3))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone4)
                    .addComponent(Bottone5)
                    .addComponent(Bottone6))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone7)
                    .addComponent(Bottone8)
                    .addComponent(Bottone9))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Bottone7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bottone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bottone4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone1ActionPerformed
        
    }//GEN-LAST:event_Bottone1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Grafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone1;
    private javax.swing.JButton Bottone2;
    private javax.swing.JButton Bottone3;
    private javax.swing.JButton Bottone4;
    private javax.swing.JButton Bottone5;
    private javax.swing.JButton Bottone6;
    private javax.swing.JButton Bottone7;
    private javax.swing.JButton Bottone8;
    private javax.swing.JButton Bottone9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
