/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package whacamole;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author compu
 */
public class Grafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Grafica.class.getName());
    private Gestore gestore = new Gestore();
    private ArrayList<JButton> bottoni = new ArrayList<>();
    private javax.swing.Timer timer;
    Gestore punti = new Gestore();
    
    
    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        
    Panel.setVisible(false);
    bottoni.add(Bottone1);
    bottoni.add(Bottone2);
    bottoni.add(Bottone3);
    bottoni.add(Bottone4);
    bottoni.add(Bottone5);
    bottoni.add(Bottone6);
    bottoni.add(Bottone7);
    bottoni.add(Bottone8);
    bottoni.add(Bottone9);

    nascondiTutto();

    timer = new javax.swing.Timer(1000, e -> mostraTalpa());
    timer.start();
        
    }
    private void nascondiTutto() {
        for (JButton b : bottoni) {
            b.setVisible(false);
        }
    }
    
    private void mostraTalpa() {
        nascondiTutto();

        int indice = gestore.esciTalpa();
        bottoni.get(indice).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Bottone1 = new javax.swing.JButton();
        Bottone2 = new javax.swing.JButton();
        Bottone3 = new javax.swing.JButton();
        Bottone4 = new javax.swing.JButton();
        Bottone5 = new javax.swing.JButton();
        Bottone6 = new javax.swing.JButton();
        Bottone7 = new javax.swing.JButton();
        Bottone8 = new javax.swing.JButton();
        Bottone9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPunteggio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bottone1.setText("Talpa1");
        Bottone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone1ActionPerformed(evt);
            }
        });

        Bottone2.setText("Talpa4");
        Bottone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone2ActionPerformed(evt);
            }
        });

        Bottone3.setText("Talpa7");
        Bottone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone3ActionPerformed(evt);
            }
        });

        Bottone4.setText("Talpa2");
        Bottone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone4ActionPerformed(evt);
            }
        });

        Bottone5.setText("Talpa5");
        Bottone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone5ActionPerformed(evt);
            }
        });

        Bottone6.setText("Talpa8");
        Bottone6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone6ActionPerformed(evt);
            }
        });

        Bottone7.setText("Talpa3");
        Bottone7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone7ActionPerformed(evt);
            }
        });

        Bottone8.setText("Talpa9");
        Bottone8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone8ActionPerformed(evt);
            }
        });

        Bottone9.setText("Talpa6");
        Bottone9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bottone9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Punteggio: ");

        txtPunteggio.setText("0");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(Bottone3)
                        .addGap(113, 113, 113)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPunteggio)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bottone9)
                                            .addComponent(Bottone7)))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Bottone6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                        .addComponent(Bottone8)))
                                .addGap(72, 72, 72))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Bottone2)
                                .addGap(113, 113, 113)
                                .addComponent(Bottone5))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Bottone1)
                                .addGap(113, 113, 113)
                                .addComponent(Bottone4)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPunteggio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Bottone7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bottone1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bottone4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottone3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bottone8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bottone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone1ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone1.setVisible(false);
    }//GEN-LAST:event_Bottone1ActionPerformed

    private void Bottone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone4ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone4.setVisible(false);
    }//GEN-LAST:event_Bottone4ActionPerformed

    private void Bottone7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone7ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone7.setVisible(false);
    }//GEN-LAST:event_Bottone7ActionPerformed

    private void Bottone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone2ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone2.setVisible(false);
    }//GEN-LAST:event_Bottone2ActionPerformed

    private void Bottone5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone5ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone5.setVisible(false);
    }//GEN-LAST:event_Bottone5ActionPerformed

    private void Bottone9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone9ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone9.setVisible(false);
    }//GEN-LAST:event_Bottone9ActionPerformed

    private void Bottone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone3ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone3.setVisible(false);
    }//GEN-LAST:event_Bottone3ActionPerformed

    private void Bottone6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone6ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone6.setVisible(false);
    }//GEN-LAST:event_Bottone6ActionPerformed

    private void Bottone8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bottone8ActionPerformed
        punti.setPunteggio(10);
        txtPunteggio.setText(" " + punti);
        Bottone8.setVisible(false);
    }//GEN-LAST:event_Bottone8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Grafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottone1;
    private javax.swing.JButton Bottone2;
    private javax.swing.JButton Bottone3;
    private javax.swing.JButton Bottone4;
    private javax.swing.JButton Bottone5;
    private javax.swing.JButton Bottone6;
    private javax.swing.JButton Bottone7;
    private javax.swing.JButton Bottone8;
    private javax.swing.JButton Bottone9;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtPunteggio;
    // End of variables declaration//GEN-END:variables
}
